apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tezos-remote-signer-forwarder
    release: monitoring
  name: tezos-remote-signer-monitoring
spec:
  selector:
    matchLabels:
      app: tezos-remote-signer-forwarder
