apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarding-ingress
spec:
  type: LoadBalancer
  selector:
    app: tezos-remote-signer-forwarder
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarder
  labels:
    app: tezos-remote-signer-forwarder
spec:
  selector:
    app: tezos-remote-signer-forwarder
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-remote-signer-loadbalancer
spec:
  selector:
    matchLabels:
      app: tezos-remote-signer-loadbalancer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-remote-signer-loadbalancer
        xtzapp: tezos-remote-signer-loadbalancer
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-remote-signer-loadbalancer
        image: tezos-remote-signer-loadbalancer
        ports:
        - containerPort: 8445
          name: signer
        envFrom:
        - configMapRef:
            name: tezos-remote-signer-loadbalancer-configmap
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-loadbalancer
  labels:
    app: tezos-remote-signer-loadbalancer
    app.type: tezos-remote-signer-loadbalancer
spec:
  ports:
  - port: 8445
    name: signer
  - port: 8404
    name: metrics
  selector:
    app: tezos-remote-signer-loadbalancer
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
  name: tezos-remote-signer-loadbalancer-monitoring
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app.type: tezos-remote-signer-loadbalancer
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
    prometheus: prometheus-xtz
    role: alert-rules
  name: tezos-remote-signer-loadbalancer-rules
spec:
  groups:
  - name: tezos-remote-signer.rules
    rules:
    - alert: NoRemoteSigner
      annotations:
        description: 'Remote signer is down'
        summary: Remote signer is down
      expr: haproxy_backend_active_servers == 0
      for: 1m
      labels:
        severity: critical
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
    prometheus: prometheus-xtz
    role: alert-rules
  name: tezos-remote-signer-rules
spec:
  groups:
  - name: tezos-remote-signer.rules
    rules:
    - alert: SignerPowerLoss
      annotations:
        description: 'Remote signer has lost power'
        summary: Tezos remote signer has lost power
      expr: power != 0
      for: 1m
      labels:
        severity: critical
    - alert: SignerWiredNetworkLoss
      annotations:
        description: 'Remote signer has lost wired internet connection'
        summary: Tezos remote signer has lost wired internet connection
      expr: wired_network != 0
      for: 1m
      labels:
        severity: critical
    - alert: SignerWirelessNetworkLoss
      annotations:
        description: 'Remote signer has lost wireless internet connection'
        summary: Tezos remote signer has lost wireless internet connection
      expr: wireless_network != 0
      for: 1m
      labels:
        severity: critical
