apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarding-ingress
spec:
  type: LoadBalancer
  selector:
    app: tezos-remote-signer-forwarder
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarder
  labels:
    app: tezos-remote-signer-forwarder
spec:
  selector:
    app: tezos-remote-signer-forwarder
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-remote-signer-loadbalancer
spec:
  selector:
    matchLabels:
      app: tezos-remote-signer-loadbalancer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-remote-signer-loadbalancer
        xtzapp: tezos-remote-signer-loadbalancer
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-remote-signer-loadbalancer
        image: tezos-remote-signer-loadbalancer
        ports:
        - containerPort: 8445
          name: signer
        envFrom:
        - configMapRef:
            name: tezos-remote-signer-loadbalancer-configmap
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-loadbalancer
  labels:
    app: tezos-remote-signer-loadbalancer
    app.type: tezos-remote-signer-loadbalancer
spec:
  ports:
  - port: 8445
    name: signer
  - port: 8404
    name: metrics
  selector:
    app: tezos-remote-signer-loadbalancer
  clusterIP: None
