---
# handlers file for tezos-remote-signer

- name: Restart ssh
  service: name=ssh state=restarted
- name: restart ufw
  service: name=ufw state=restarted
- name: restart fowarder
  service: name=tezos-signer-forwarder state=restarted
