apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tezos-public-node-rpc
spec:
  backend:
    serviceName: tezos-public-node
    servicePort: rpc
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: node-rpc-certificate
spec:
  domains:
  - ${rpc_public_hostname}
