apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tezos-public-node-rpc
spec:
  backend:
    serviceName: tezos-public-node
    servicePort: rpc
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: node-rpc-certificate
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: node-rpc-backendconfig
