---
# install tezos as tezos user
#
- git:
    repo: 'https://gitlab.com/tezos/tezos.git'
    dest: /home/tezos/tezos
    version: alphanet

- name: install ocaml environment
  shell: | 
    cd /home/tezos/tezos
    opam init --bare --auto-setup
    opam switch create tezos ocaml-base-compiler.4.07.1
    eval $(opam env)
    make build-deps
    make
  register: tezosinstall

- debug: msg="{{ tezosinstall.stdout }}"

- debug: msg="{{ tezosinstall.stderr }}"
