apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  SNAPSHOT_URL: "{{ .Values.snapshotUrl }}"
  PUBLIC_BAKING_KEY: "{{ .Values.publicBakingKey }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-baker-configmap
data:
  NODE_HOST: "localhost"
  PROTOCOL: "004-Pt24m4xi"
  REMOTE_SIGNER_URL: "http://tezos-remote-signer-forwarder:8443/{{ .Values.publicBakingKey }}"
  DATA_DIR: /var/run/tezos
