apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarding-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 58255
    targetPort: 58255
    name: ssh-forwarding-ingress
  selector:
    app: tezos-remote-signer-forwarder
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-remote-signer-forwarder
spec:
  selector:
    app: tezos-remote-signer-forwarder
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tezos-remote-signer-forwarder
    release: monitoring
  name: tezos-remote-signer-monitoring
spec:
  selector:
    matchLabels:
      app: tezos-remote-signer-forwarder
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tezos-remote-signer-forwarder-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tezos-remote-signer-forwarder
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 58255
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-remote-signer-forwarder
spec:
  selector:
    matchLabels:
      app: tezos-remote-signer-forwarder
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-remote-signer-forwarder
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-remote-signer-forwarder
        image: tezos-remote-signer-forwarder
        ports:
        - containerPort: 58255
          name: ssh
        env:
        - name: SIGNER_DATA
          valueFrom:
            configMapKeyRef:
              name: remote-signer-forwarder-configmap
              key: SIGNER_DATA
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
