apiVersion: v1
kind: Service
metadata:
  name: tezos-private-baking-node
  labels:
    app: tezos-private-baking-node
spec:
  ports:
  - port: 9732
    name: p2p
  - port: 9489
    name: metrics
  - port: 4247
    name: nonce-exposer
  selector:
    app: tezos-private-baking-node
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tezos-private-baking-node-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tezos-private-baking-node
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  - ports:
    - port: 4247
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: tezos-private-baking-node
  - ports:
    - port: 8445
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          xtzapp: tezos-remote-signer-loadbalancer
  - ports:
    - port: 9732
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: tezos-public-node
  ingress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  - ports:
    - port: 9489
      protocol: TCP
    from:
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels:
          app: prometheus
  - ports:
    - port: 9732
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: tezos-public-node
  - ports:
    - port: 4247
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: tezos-private-baking-node
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tezos-remote-signer-loadbalancer-policy
spec:
  podSelector:
    matchLabels:
      xtzapp: tezos-remote-signer-loadbalancer
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8445
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: tezos-private-baking-node
  - ports:
    - port: 8404
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: prometheus
      namespaceSelector:
        matchLabels: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-private-baking-node
spec:
  replicas: 2
  serviceName: "tezos-private-baking-node"
  selector:
    matchLabels:
      app: tezos-private-baking-node
  template:
    metadata:
      labels:
        app: tezos-private-baking-node
    spec:
      securityContext:
        fsGroup: 100
      serviceAccountName: tzt-leader-elector
      containers:
      - name: tezos-private-node
        image: tezos/tezos
        args: [ "tezos-node" ]
        ports:
        - containerPort: 9732
          name: tezos-port
        - containerPort: 8732
          name: tezos-rpc-port
        volumeMounts:
        - name: tezos-private-node-pv-claim
          mountPath: /var/run/tezos
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      - name: tezos-prometheus-exporter
        image: ecadlabs/tezos_exporter
        args: [ "-tezos-node-url", "http://localhost:8732/" ]
        ports:
        - containerPort: 9489
          name: metrics
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      - name: tezos-accuser
        image: tezos/tezos
        args: [ "tezos-accuser" ]
        env:
        - name: NODE_HOST
          valueFrom:
            configMapKeyRef:
              name: tezos-private-node-configmap
              key: NODE_HOST
        - name: PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: tezos-private-node-configmap
              key: PROTOCOL
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      - name: leader-elector
        image: k8s.gcr.io/leader-elector:0.5
        args: [ "--election=baker", "--http=0.0.0.0:4040" ]
        resources:
          limits:
            cpu: 0
      - name: tezos-nonce-exposer
        image: tezos-nonce-exposer
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: tezos-private-node-pv-claim
          mountPath: /var/run/tezos
        imagePullPolicy: Always
        ports:
        - containerPort: 4247
          name: nonce-exposer
      - name: tezos-nonce-importer
        image: tezos-nonce-importer
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: tezos-private-node-pv-claim
          mountPath: /var/run/tezos
        imagePullPolicy: Always
      initContainers:
      - name: tezos-private-node-configurator
        image: tezos-private-node-configurator
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: tezos-private-node-pv-claim
          mountPath: /var/run/tezos
        envFrom:
        - configMapRef:
            name: tezos-private-node-configmap
        imagePullPolicy: Always
      - name: tezos-snapshot-downloader
        image: tezos-snapshot-downloader
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: tezos-private-node-pv-claim
          mountPath: /var/run/tezos
        env:
        - name: TEZOS_NETWORK
          valueFrom:
            configMapKeyRef:
              name: tezos-private-node-configmap
              key: TEZOS_NETWORK
        - name: SNAPSHOT_URL
          valueFrom:
            configMapKeyRef:
              name: tezos-private-node-configmap
              key: SNAPSHOT_URL
        imagePullPolicy: Always
      - name: tezos-key-importer
        image: tezos-key-importer
        env:
        - name: KUBERNETES_NAME_PREFIX
          valueFrom:
            configMapKeyRef:
              name: tezos-private-node-configmap
              key: KUBERNETES_NAME_PREFIX
        - name: SIGNER_DATA
          valueFrom:
            secretKeyRef:
              name: signer-secret
              key: SIGNER_DATA
        volumeMounts:
        - name: tezos-private-node-pv-claim
          mountPath: /var/run/tezos
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
  name: tezos-private-node-monitoring
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: tezos-private-baking-node
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
    prometheus: prometheus-xtz
    role: alert-rules
  name: tezos-private-node-rules
spec:
  groups:
  - name: tezos-private-node
    rules:
    - alert: PrivateNodeLost1Connection
      annotations:
        description: 'Private node lost one connection to pubic node'
        summary: Private node has less than the expected number of connections
      expr: sum(tezos_node_connections{private="false",pod=~".*-tezos-private-baking-node-.*"}) < 2
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
    - alert: PrivateNodeDisconnected
      annotations:
        description: 'Private node lost all connections to public nodes'
        summary: Private node has no connnection to public nodes
      expr: sum(tezos_node_connections{private="false",pod=~".*-tezos-private-baking-node-.*"}) == 0
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
