kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
    prometheus: prometheus-xtz
    role: alert-rules
  name: tezos-public-node-rules
spec:
  groups:
  - name: tezos-public-node
    rules:
    - alert: NodeSyncing
      annotations:
        description: 'Node is not synced'
        summary: Node reports not being bootstrapped
      expr: tezos_node_bootstrapped != 1
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
    - alert: PublicNodeFewConnections
      annotations:
        description: 'Public node has less than 5 connections.'
        summary: Private node has less than the expected number of connections
      expr: sum(tezos_node_connections{private="false",pod=~".*-tezos-public-node-.*"}) < 5
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
    - alert: PublicNodeDisconnected
      annotations:
        description: 'Public node is disconnected'
        summary: Public node has no connections to the tezos network
      expr: sum(tezos_node_connections{private="false",pod=~".*-tezos-public-node-.*"}) == 0
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
---
# for private node leader election, access to endpoint resource is needed
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-elector
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: leader-elector
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-elector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-elector
subjects:
- kind: ServiceAccount
  name: leader-elector
  namespace: default
