kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-public-node
  labels:
    app: tezos-public-node
spec:
  ports:
  - port: 9732
    name: p2p
  - port: 9489
    name: metrics
  - port: 8732
    name: rpc
  selector:
    app: tezos-public-node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
  name: tezos-public-node-monitoring
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: tezos-public-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tezos-public-node
spec:
  selector:
    matchLabels:
      app: tezos-public-node # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "tezos-public-node"
  template:
    metadata:
      labels:
        app: tezos-public-node # Pod template's label selector
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - name: tezos-public-node
        image: tezos-public-node-with-probes
        command: [ "/usr/local/bin/tezos-node", "run", "--data-dir", "/var/run/tezos/node/data" ]
        ports:
        - containerPort: 8732
          name: rpc
        - containerPort: 9732
          name: tezos-port
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        resources:
          limits:
            cpu: 0
        env:
        - name: TEZOS_NETWORK
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: TEZOS_NETWORK
        imagePullPolicy: Always
      initContainers:
      - name: tezos-public-node-configurator
        image: tezos-public-node-configurator
        env:
        - name: PRIVATE_PEER_LIST
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: PRIVATE_PEER_LIST
        - name: HISTORY_MODE
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: HISTORY_MODE
        - name: TEZOS_NETWORK
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: TEZOS_NETWORK
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
      - name: tezos-snapshot-downloader
        image: tezos-snapshot-downloader
        volumeMounts:
        - name: tezos-public-node-pv-claim
          mountPath: /var/run/tezos/node
        env:
        - name: SNAPSHOT_URL
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: SNAPSHOT_URL
        - name: TEZOS_NETWORK
          valueFrom:
            configMapKeyRef:
              name: tezos-configmap
              key: TEZOS_NETWORK
        resources:
          limits:
            cpu: 0
        imagePullPolicy: Always
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-xtz
    release: mon-xtz
    prometheus: prometheus-xtz
    role: alert-rules
  name: tezos-public-node-rules
spec:
  groups:
  - name: tezos-public-node
    rules:
    - alert: NodeSyncing
      annotations:
        description: 'Node is not synced'
        summary: Node reports not being bootstrapped
      expr: tezos_node_bootstrapped != 1
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
    - alert: PublicNodeFewConnections
      annotations:
        description: 'Public node has less than 5 connections.'
        summary: Private node has less than the expected number of connections
      expr: sum(tezos_node_connections{private="false",pod=~".*-tezos-public-node-.*"}) < 5
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
    - alert: PublicNodeDisconnected
      annotations:
        description: 'Public node is disconnected'
        summary: Public node has no connections to the tezos network
      expr: sum(tezos_node_connections{private="false",pod=~".*-tezos-public-node-.*"}) == 0
      for: 1m
      labels:
        alerting_target: blockchain_cluster_alerter
        severity: critical
---
# for private node leader election, access to endpoint resource is needed
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-elector
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: leader-elector
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leader-elector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leader-elector
subjects:
- kind: ServiceAccount
  name: leader-elector
  namespace: default
